### PR TITLE
Resources for operator release 18.0.0

### PR DESCRIPTION
**Pull request by andreaTP**
After this is merged we need to push the relevant tag(and or branch) as well.

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]

**Comment by diversit** [comment]
Shouldn't this be the resources for the new Keycloak Operator v20.x ?
The `keycloaks` and `keycloakrealmimports` seem to have the new apiVersion, but the deployment files refer to image version 18.x. Should that not be 20.x?

I want to take a look at the new operator but the information is very scarse and hard to find.

**Comment by vmuzikar** [comment]
Hello, thank you for your interest in the Operator. It is actually v18. It is released as 20.0.0-alpha.1 only on OperatorHub to avoid version conflicts with the old legacy operator (which last version will be 19.y.z). See our [release notes](https://www.keycloak.org/2022/04/keycloak-1800-released).

**Comment by diversit** [comment]
@vmuzikar Thanks for explanation. It's still confusing I think. Also because the [Operator Guides](https://www.keycloak.org/guides#operator) has no distinction between the 'new' and 'legacy' so I don't know for which version I'm reading.

**Comment by vmuzikar** [comment]
@diversit The operator guides are implicitly for the new one, unless said otherwise like e.g. [here](https://www.keycloak.org/getting-started/getting-started-operator-openshift).

**Pull request merged**
